DWAPlannerROS: 

  acc_lim_theta: 4.0
  acc_lim_x: 1.5
  acc_lim_y: 0.0 


  max_vel_x: 0.4 
  min_vel_x: 0.0 

  max_vel_y: 0.0 
  min_vel_y: 0.0

  max_trans_vel: 0.4 
  min_trans_vel: 0.1 
  max_rot_vel: 0.7
  min_rot_vel: 0.4
  
  acc_limit_trans: 0.5

  sim_time: 1.5

  sim_granularity: 0.05
  goal_distance_bias: 12.0 
  path_distance_bias: 32.0 
  occdist_scale: 0.01 
  stop_time_buffer: 0.2 
  oscillation_reset_dist: 0.1 
  forward_point_distance: 0.4
  scaling_speed: 0.2
  max_scaling_factor: 0.2 
  vx_samples: 8
  vy_samples: 0 
  vth_samples: 10
  xy_goal_tolerance: 0.04
  yaw_goal_tolerance: 0.06 
  rot_stopped_vel: 0.08 
  trans_stopped_vel: 0.01
