# Move_base node parameters

controller_frequency: 5.0
planner_patience: 1.0

controller_patience: 10.0
conservative_reset_dist: 0.5

recovery_behavior_enabled: false
clearing_rotation_allowed: true

shutdown_costmaps: false

oscillation_timeout: 0.0
oscillation_distance: 0.5

planner_frequency: 0.0
max_planning_retries: 1
